name: Run Tests

on:
  pull_request:
  push:
    branches:
      - '**'

env:
  nim-version: 'stable'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: nimble install -Y

      - name: Run Tests C (Normal Usage)
        run: nimble test

      - name: Run Tests C (Locks Disabled)
        run: nimble test -d:nulidNoLocks

      - name: Run Tests C (Insecure Random)
        run: nimble test -d:nulidInsecureRandom

      - name: Run Tests C (Insecure Random & Locks Disabled)
        run: nimble test -d:nulidInsecureRandom -d:nulidNoLocks

      - name: Run Tests JS (Normal Usage; Locks Disabled by Default)
        run: nimble test -b:js

      - name: Run Tests JS (Insecure Random)
        run: nimble test -b:js -d:nulidInsecureRandom